# Generated by Django 2.2.6 on 2019-10-18 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_adicionadas', models.IntegerField(default=0)),
                ('horas_usadas', models.IntegerField(default=0)),
                ('descricao', models.CharField(default='Nao informado', max_length=150)),
                ('aprovado', models.BooleanField(default=False)),
                ('militar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cadastro', to='cadastro.Cadastro')),
            ],
            options={
                'verbose_name_plural': 'Banco De Horas',
            },
        ),
    ]
