# Generated by Django 2.2.6 on 2019-10-10 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_adicionadas', models.TimeField(default=0)),
                ('horas_usadas', models.TimeField(default=0)),
                ('descricao', models.CharField(default='Nao informado', max_length=150)),
                ('militar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cadastro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
