# Generated by Django 2.2.6 on 2019-10-18 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancohoras',
            name='militar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Cadastro'),
        ),
    ]
