# Generated by Django 2.2.6 on 2019-10-18 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_auto_20191018_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancohoras',
            name='militar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Cadastro'),
        ),
    ]
