# Generated by Django 2.2.6 on 2019-10-10 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_auto_20191010_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancohoras',
            name='militar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cadastro', to=settings.AUTH_USER_MODEL),
        ),
    ]
