# Generated by Django 2.2.6 on 2019-10-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_auto_20191010_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancohoras',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
