# Generated by Django 2.2.6 on 2019-10-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bancohoras',
            options={'verbose_name_plural': 'Banco De Horas'},
        ),
        migrations.AlterField(
            model_name='bancohoras',
            name='horas_adicionadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bancohoras',
            name='horas_usadas',
            field=models.IntegerField(default=0),
        ),
    ]
