# Generated by Django 2.2.6 on 2019-10-17 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalQdi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Local Qdi',
            },
        ),
        migrations.CreateModel(
            name='LocalQo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Local Qo',
            },
        ),
        migrations.CreateModel(
            name='Locais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localQdi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locais.LocalQdi')),
                ('localQo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locais.LocalQo')),
            ],
            options={
                'verbose_name_plural': 'Locais',
            },
        ),
    ]
