# Generated by Django 2.2.6 on 2019-10-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localqdi',
            name='sigla',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localqo',
            name='sigla',
            field=models.CharField(default='sds', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localqdi',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='localqo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
