# Generated by Django 2.2.6 on 2019-10-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0002_auto_20191017_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='localqdi',
            name='localAdido',
            field=models.CharField(default='serra', max_length=150),
            preserve_default=False,
        ),
    ]
