# Generated by Django 2.2.6 on 2019-10-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0003_localqdi_localadido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localqdi',
            name='localAdido',
        ),
        migrations.AddField(
            model_name='locais',
            name='localAdido',
            field=models.CharField(default='serra', max_length=150),
            preserve_default=False,
        ),
    ]
