# Generated by Django 2.2.6 on 2019-10-17 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0004_auto_20191017_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locais',
            name='localAdido',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='locais',
            name='localQdi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locais.LocalQdi'),
        ),
        migrations.AlterField(
            model_name='locais',
            name='localQo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locais.LocalQo'),
        ),
        migrations.AlterField(
            model_name='localqdi',
            name='nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='localqdi',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='localqo',
            name='nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='localqo',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
