# Generated by Django 2.2.6 on 2019-10-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0005_auto_20191017_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localqdi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='localqo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
