# Generated by Django 2.2.6 on 2019-10-17 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postoGraduacao', models.CharField(max_length=12)),
                ('nome', models.CharField(max_length=90)),
                ('oficial', models.BooleanField()),
                ('nomeGuerra', models.CharField(max_length=30)),
                ('numeroFuncional', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=15)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locais.Locais')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
