# Generated by Django 2.2.6 on 2019-10-18 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postoGraduacao', models.CharField(blank=True, max_length=12, null=True)),
                ('nome', models.CharField(blank=True, max_length=90, null=True)),
                ('oficial', models.BooleanField(blank=True, null=True)),
                ('nomeGuerra', models.CharField(blank=True, max_length=30, null=True)),
                ('numeroFuncional', models.CharField(blank=True, max_length=10, null=True)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('localQdi', models.CharField(blank=True, max_length=150, null=True)),
                ('localQo', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cadastro',
            },
        ),
    ]
