# Generated by Django 2.2.6 on 2019-10-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='oficial',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
