# Generated by Django 2.2.6 on 2019-10-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locais.Locais'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nomeGuerra',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='numeroFuncional',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='oficial',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='postoGraduacao',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
