# Generated by Django 2.2.6 on 2019-10-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20191018_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(blank=True, default='nao encontrado', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='localQdi',
            field=models.CharField(blank=True, default='nao encontrado', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='localQo',
            field=models.CharField(blank=True, default='nao encontrado', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(blank=True, default='nao encontrado', max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nomeGuerra',
            field=models.CharField(blank=True, default='nao encontrado', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='numeroFuncional',
            field=models.CharField(blank=True, default='nao encontrado', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='oficial',
            field=models.CharField(blank=True, default='E', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='postoGraduacao',
            field=models.CharField(blank=True, default='nao encontrado', max_length=12, null=True),
        ),
    ]
